# Generated by Django 2.1 on 2019-07-06 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20190706_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='comment.Comment', verbose_name='父评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='选中显示'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_comment', to='comment.Comment', verbose_name='根评论'),
        ),
    ]
