# Generated by Django 2.1 on 2019-06-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_delete',
        ),
    ]
