# Generated by Django 2.1 on 2019-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190701_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-article_order', '-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='article',
            name='article_order',
            field=models.IntegerField(default=0, verbose_name='排序,数字越大越靠前'),
        ),
    ]
